const { PGlite } = require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
(async()=>{
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;
create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.uid',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select jsonb_build_object('email',current_setting('request.email',true))$$;
grant usage on schema public,auth to authenticated,anon,service_role;
grant execute on function auth.uid(),auth.jwt() to authenticated,anon,service_role;`);
await db.exec(fs.readFileSync(path.join(root,'supabase-schema.sql'),'utf8').replace(/^\uFEFF/,''));
await db.exec(fs.readFileSync(path.join(root,'supabase-upgrade.sql'),'utf8'));
await db.exec(fs.readFileSync(path.join(root,'supabase-photos.sql'),'utf8'));
console.log('PASS Base schema and upgrade execute');
await db.exec(fs.readFileSync(path.join(root,'supabase-upgrade.sql'),'utf8'));
console.log('PASS Upgrade is rerunnable');
await db.query(`insert into auth.users(id,email) values($1,'vinicius@peleja.invalid'),($2,'wilton@peleja.invalid')`,[A,B]);
await db.query(`insert into public.account_handles values($1,'vinicius',true),($2,'wilton',true)`,[A,B]);
async function user(id){await db.exec('reset role');await db.query("select set_config('request.uid',$1,false)",[id||'']);await db.exec('set role authenticated');}
async function rpc(name,params,casts){const placeholders=params.map((_,i)=>'$'+(i+1)+(casts?.[i]?'::'+casts[i]:''));return (await db.query(`select public.${name}(${placeholders}) as result`,params)).rows[0].result;}
const ws={materials:[{id:'m',title:'Aula',subject:'Pediatria',questionEntries:[{id:'q',questions:10,correct:8,wrong:2}],notes:'PRIVATE',read:true}],exams:[{id:'e',subject:'Pediatria',type:'Prova',date:'2026-09-28',materialIds:['m'],total:10,correct:8,wrong:2}],simulations:[{id:'s',name:'Evento',date:'2026-09-28',questions:[{id:'q1',number:1,correctAnswer:'A',area:'Pediatria'},{id:'q2',number:2,correctAnswer:'B',area:'Cirurgia'}]}]};
async function save(payload,revision,cat,publish){return rpc('save_workspace',[JSON.stringify(payload),revision,cat,publish,(await db.query('select auth.uid() id')).rows[0].id],['jsonb','bigint','bigint','boolean','uuid']);}
await db.exec(fs.readFileSync(path.join(root,'supabase-photos.sql'),'utf8'));
await user(A); await rpc('save_profile_photo',['data:image/jpeg;base64,YQ=='],['text']);
await user(B); assert.equal((await db.query('select * from public.profile_photos')).rows.length,1);
await assert.rejects(()=>db.query('update public.profile_photos set image_data=$1 where user_id=$2',['data:image/jpeg;base64,Yg==',A]),/permission denied/);
await rpc('save_profile_photo',['data:image/jpeg;base64,Yg=='],['text']);
await rpc('save_profile_photo',[null],['text']);
assert.equal((await db.query('select * from public.profile_photos')).rows[0].user_id,A);
await assert.rejects(()=>rpc('save_profile_photo',['https://external.test/photo'],['text']),/check constraint/);
await assert.rejects(()=>rpc('save_profile_photo',['data:image/jpeg;base64,'+'A'.repeat(60000)],['text']),/check constraint/);
console.log('PASS Private photos: own update/remove only, invalid and oversized images rejected');
await user(A);let saved=await save(ws,0,0,true);assert.equal(saved.revision,1);assert.equal(saved.catalog_revision,1);
console.log('PASS Admin publishes canonical catalog and own result atomically');
let data=await rpc('get_workspace',[],[]);assert.equal(data.payload.materials[0].notes,'PRIVATE');assert(!JSON.stringify(data.catalog).includes('PRIVATE'));assert(!('total' in data.catalog.exams[0]));
console.log('PASS Shared catalog excludes private notes and personal results');
await user(B);
await assert.rejects(()=>rpc('save_workspace',[JSON.stringify(ws),0,1,false,A],['jsonb','bigint','bigint','boolean','uuid']),/conta mudou/);
assert.equal((await db.query('select count(*) n from public.user_workspace')).rows[0].n,0);
await user(A);
console.log('PASS Mismatched transport identity cannot save the previous account payload');
await assert.rejects(()=>save(ws,0,1,true),/CONFLICT/);
assert.equal((await rpc('get_workspace',[],[])).revision,1);
console.log('PASS Stale revision cannot overwrite newer data');
await user(B);data=await rpc('get_workspace',[],[]);assert.equal(data.payload,null);assert.equal(data.catalog.exams.length,1);
assert.equal((await db.query('select * from public.user_workspace')).rows.length,0);
await assert.rejects(()=>save(ws,0,1,true),/Somente Vinícius/);
await assert.rejects(()=>db.query("update public.simulation_questions set official_answer='E'"),/permission denied/);
await assert.rejects(()=>db.query("select public.rebuild_simulation_results('res::s')"),/permission denied/);
console.log('PASS Participant cannot read another private workspace, publish catalog or call privileged helpers');
const own=JSON.parse(JSON.stringify(ws));own.exams[0].correct=3;own.exams[0].wrong=7;own.materials[0].notes='B note';
await save(own,0,1,false);assert.equal((await db.query('select * from public.university_results where user_id=$1',[B])).rows[0].correct,3);
let basis=(await rpc('simulation_bases',[],[]))['res::s'];
async function attempt(mode,answers,correct,areas,b=basis,votes={}){return rpc('save_simulation_attempt',['res::s',mode,JSON.stringify(answers),JSON.stringify(votes),correct,JSON.stringify(areas),b,(await db.query('select auth.uid() id')).rows[0].id],['text','text','jsonb','jsonb','integer','jsonb','text','uuid']);}
await attempt('answers',{'1':'A','2':'C'},null,{});
assert.equal((await db.query('select * from public.simulation_results where user_id=$1',[B])).rows[0].correct,1);
await assert.rejects(()=>attempt('quick',{},3,{}),/Acertos totais/);
assert.equal((await db.query('select * from public.simulation_user_answers where user_id=$1',[B])).rows.length,2);
console.log('PASS Failed quick conversion rolls back and preserves detailed answers');
await attempt('quick',{},1,{'Pediatria':1,'Cirurgia':0});
assert.equal((await db.query('select * from public.simulation_user_answers where user_id=$1',[B])).rows.length,0);
assert.equal((await db.query('select * from public.simulation_manual_results where user_id=$1',[B])).rows[0].correct,1);
await assert.rejects(()=>attempt('answers',{'1':'A'},null,{}),/Preencha/);
assert.equal((await db.query('select * from public.simulation_manual_results where user_id=$1',[B])).rows.length,1);
console.log('PASS Failed detailed conversion preserves quick result; successful conversion replaces atomically');
await user(A);ws.simulations[0].questions[0].correctAnswer='C';saved=await save(ws,1,1,true);basis=(await rpc('simulation_bases',[],[]))['res::s'];
await user(B);const old=(await db.query('select basis from public.simulation_manual_results where user_id=$1',[B])).rows[0].basis;assert.notEqual(old,basis);
await assert.rejects(()=>attempt('quick',{},1,{},old),/CONFLICT/);
console.log('PASS Key changes invalidate quick-result basis and reject stale submissions');
await user(A);ws.exams=[];ws.materials=[];ws.simulations=[];await save(ws,2,2,true);
assert.equal((await db.query('select * from public.simulation_catalog')).rows.length,0);
assert.equal((await db.query('select * from public.university_results')).rows.length,0);
console.log('PASS Explicit catalog deletions remove shared events and all linked ranking results');
await db.exec('reset role');await db.query('update public.account_handles set active=false where user_id=$1',[B]);await user(B);
await assert.rejects(()=>rpc('get_workspace',[],[]),/Acesso negado/);
assert.equal((await db.query('select * from public.simulation_manual_results')).rows.length,0);
assert.equal((await db.query('select * from public.profile_photos')).rows.length,0);
await assert.rejects(()=>rpc('save_profile_photo',['data:image/jpeg;base64,YQ=='],['text']),/Acesso negado/);
console.log('PASS Revoked account cannot access data or photos');
await db.exec('reset role;set role anon');await assert.rejects(()=>rpc('get_workspace',[],[]),/permission denied/);
await assert.rejects(()=>db.query('select * from public.profile_photos'),/permission denied/);
await assert.rejects(()=>rpc('save_profile_photo',[null],['text']),/permission denied/);
console.log('PASS Anonymous access denied');
await db.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
