const {JSDOM}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,n),'utf8');
const dom=new JSDOM(read('index.html'),{url:'file:///test/index.html',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;
const stored=new Map();Object.defineProperty(w,'localStorage',{value:{getItem:k=>stored.get(k)??null,setItem:(k,v)=>stored.set(k,String(v)),removeItem:k=>stored.delete(k)}});
w.PELEJA_BACKEND={};w.PELEJA_ACADEMIC_DATA={materials:[],exams:[]};w.fetch=async()=>({ok:false});w.confirm=()=>true;
try {
  w.eval(read('storage.js'));
  w.eval(read('app.js').replace(/\}\)\(\);\s*$/,'globalThis.__materials={state,els,openMaterialModal,handleMaterialSubmit,renderReadingQueue,todayDateValue};\n})();'));
  const api=w.__materials, {state,els}=api, today=api.todayDateValue();
  const exam=(id,date,ids=[],subject='Pediatria')=>({id,date,materialIds:ids,subject,type:'PR1',total:10,correct:8,wrong:2,source:'preserve'});
  state.materials=[];
  state.exams=[exam('past','2000-01-01'),exam('today',today),exam('later','2099-12-31'),exam('other',today,[],'Cirurgia')];
  api.openMaterialModal();assert.equal(els.classDateInput.value,today);
  els.subjectInput.value='Pediatria';els.subjectInput.dispatchEvent(new w.Event('input'));
  const checked=()=>[...w.document.querySelectorAll('#materialExamOptions input:checked')].map(i=>i.value);
  assert.deepEqual(checked(),['today']);
  els.titleInput.value='Apostila nova';els.classDateInput.value='2026-09-15';
  w.document.querySelector('#materialExamOptions input[value="later"]').checked=true;
  api.handleMaterialSubmit({preventDefault(){}});
  const created=state.materials[0];assert.equal(created.classDate,'2026-09-15');
  assert(state.exams.find(e=>e.id==='today').materialIds.includes(created.id));
  assert(state.exams.find(e=>e.id==='later').materialIds.includes(created.id));
  assert.equal(state.exams.find(e=>e.id==='today').correct,8);
  assert.equal(state.exams.find(e=>e.id==='today').source,'preserve');
  assert(JSON.parse(w.PELEJA_STORAGE.getItem('medstudy_exams_v1')).find(e=>e.id==='today').materialIds.includes(created.id));
  api.openMaterialModal(created);assert.equal(els.classDateInput.value,'2026-09-15');assert.deepEqual(checked(),['today','later']);
  w.document.querySelector('#materialExamOptions input[value="today"]').checked=false;
  api.handleMaterialSubmit({preventDefault(){}});assert(!state.exams.find(e=>e.id==='today').materialIds.includes(created.id));
  assert(state.exams.find(e=>e.id==='later').materialIds.includes(created.id));
  api.openMaterialModal(state.materials[0]);els.subjectInput.value='Cirurgia';els.subjectInput.dispatchEvent(new w.Event('input'));
  api.handleMaterialSubmit({preventDefault(){}});assert(!state.exams.find(e=>e.id==='later').materialIds.includes(created.id));
  state.exams.push(exam('tie',today));
  api.openMaterialModal();els.subjectInput.value='Pediatria';els.subjectInput.dispatchEvent(new w.Event('input'));assert.equal(checked().length,0,'No arbitrary choice between same-day exams');
  els.subjectInput.value='Sem provas';els.subjectInput.dispatchEvent(new w.Event('input'));els.titleInput.value='Sem vínculo';api.handleMaterialSubmit({preventDefault(){}});
  assert(state.materials.some(m=>m.title==='Sem vínculo'));
  const material=(id,read=false)=>({id,title:id,subject:'Pediatria',classDate:'2026-01-01',classOrder:'',createdAt:'2026-01-01',read});
  state.materials=['past-only','future','today','unlinked','both'].map(id=>material(id));state.materials.push(material('read',true));
  state.exams=[exam('p','2000-01-01',['past-only','both']),exam('f','2099-01-01',['future','both','read']),exam('t',today,['today'])];
  api.renderReadingQueue();const queue=w.document.getElementById('readingQueue').textContent;
  assert(!queue.includes('past-only'));for(const id of ['future','today','unlinked','both'])assert(queue.includes(id));
  state.materials=[material('past-only')];api.renderReadingQueue();assert.match(w.document.getElementById('readingQueue').textContent,/provas passadas continuam na biblioteca/);
  assert.equal(state.materials[0].read,false,'Dashboard never marks past material as read');
  console.log('PASS Material date default, editable date, exam suggestion, ambiguity, multiple links, persistence, subject change and reading queue');
} finally {w.close();}
